
spring:
   redis:
      host: 127.0.0.1
      port: 6379
   
   datasource:
      url: jdbc:h2:tcp://localhost/~/RestAPIProject
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver
   
   jpa:
      hibernate:
         ddl-auto: update
      
      properties:
         hibernate:
            show_sql: true
            format_sql: true
      
      open-in-view: false
      
   messages:
      basename: i18n/exception
      encoding: UTF-8

   thymeleaf:
      cache: false

   devtools:
      livereload:
         enabled: true
      remote:
         restart:
            enabled: true

jwt:
   secret: aGFyZGVuc3ByaW5nc2VjdXJpdHlzdHVkeQ== # 임의의 문자열을 Base64로 인코딩
   access.token.expire.time: 3600 # 1시간 (60초 * 60 = 1시간)
   refresh.token.expire.time: 1296000 # 15일 (60초 * 60 = 1시간 -> 1시간 * 24 = 24시간 -> 24시간 * 15 = 15일)

#logging.level.org.hibernate:
#   SQL: debug
#   type.descriptor.sql: trace








