INSERT INTO ROLE (ROLE_ID, ROLE_TYPE, PARENT_ROLE_ID) VALUES (1, 'ROLE_ADMIN'    , null);
INSERT INTO ROLE (ROLE_ID, ROLE_TYPE, PARENT_ROLE_ID) VALUES (2, 'ROLE_USER'     , 1);
INSERT INTO ROLE (ROLE_ID, ROLE_TYPE, PARENT_ROLE_ID) VALUES (3, 'ROLE_ANONYMOUS', 2);
INSERT INTO ROLE (ROLE_ID, ROLE_TYPE, PARENT_ROLE_ID) VALUES (4, 'ROLE_MANAGER'  , 1);

INSERT INTO RESOURCE(RESOURCE_ID, REQUEST_MATCHER, RESOURCE_NAME, RESOURCE_TYPE, HTTP_METHOD)
VALUES(1, '/api/admin/*', 'ADMIN 정보 조회', 'API_RESOURCE', 'GET');

INSERT INTO RESOURCE(RESOURCE_ID, REQUEST_MATCHER, RESOURCE_NAME, RESOURCE_TYPE, HTTP_METHOD)
VALUES(2, '/api/user/*', 'User 정보 조회', 'API_RESOURCE', 'GET');

INSERT INTO RESOURCE(RESOURCE_ID, REQUEST_MATCHER, RESOURCE_NAME, RESOURCE_TYPE, HTTP_METHOD)
VALUES(3, '/api/user', 'User 데이터 생성', 'API_RESOURCE', 'POST');

INSERT INTO RESOURCE(RESOURCE_ID, REQUEST_MATCHER, RESOURCE_NAME, RESOURCE_TYPE, HTTP_METHOD)
VALUES(4, '/api/info', 'INFO 데이터 생성', 'API_RESOURCE', 'POST');

INSERT INTO RESOURCE_ROLE(RESOURCE_ROLE_ID, RESOURCE_ID, ROLE_ID)
VALUES(1, 1, 1);

INSERT INTO RESOURCE_ROLE(RESOURCE_ROLE_ID, RESOURCE_ID, ROLE_ID)
VALUES(2, 2, 2);

INSERT INTO RESOURCE_ROLE(RESOURCE_ROLE_ID, RESOURCE_ID, ROLE_ID)
VALUES(3, 2, 4);

INSERT INTO RESOURCE_ROLE(RESOURCE_ROLE_ID, RESOURCE_ID, ROLE_ID)
VALUES(4, 3, 3);

INSERT INTO MEMBER (MEMBER_ID, NAME, PASSWORD, USER_ID, ROLE_ID)
VALUES(1, 'admin', '1234', 'admin', 1);